name: Furnace
version: "0.0.1"
author: Palente and Translator KRUNCHSHooT1140
main: Palente\Furnace\Main
description: "A /furnace command by Palente and Translator KRUNCHSHooT1140"
website: "https://github.com/KRUNCHSHooT1140"

api: 
  - "3.0.0"
  - "3.0.2"
  - "4.0.0"
permissions:
  Furnace:
    description: "Main permission of plugin furnace"
    children:
      Furnace.use:
        description: "Use the /furnace"
        default: op
